import { assertSchemaRequirements } from "@/lib/schemaRequirements";

export async function ensureTriageIncidentTables(): Promise<void> {
  await assertSchemaRequirements(
    "ensureTriageIncidentTables",
    [
      {
        table: "triage_incidents",
        columns: [
          "id",
          "incident_code",
          "source_case_uid",
          "mode",
          "status",
          "address",
          "aware_date",
          "summary",
          "notes",
          "created_by_team_id",
          "approved_by_dispatch_user_id",
          "command_team_id",
          "start_red_count",
          "start_yellow_count",
          "start_green_count",
          "start_black_count",
          "pat_red_count",
          "pat_yellow_count",
          "pat_green_count",
          "pat_black_count",
        ],
        indexes: [
          "idx_triage_incidents_source_case_uid",
          "idx_triage_incidents_mode_status_updated",
          "idx_triage_incidents_command_team",
        ],
      },
      {
        table: "triage_incident_teams",
        columns: [
          "id",
          "incident_id",
          "team_id",
          "role",
          "participation_status",
          "operational_mode_at_request",
          "triage_mode_requested_at",
          "triage_mode_acknowledged_at",
          "last_seen_at",
        ],
        indexes: [
          "idx_triage_incident_teams_incident_role",
          "idx_triage_incident_teams_team_status",
        ],
      },
      {
        table: "triage_patients",
        columns: [
          "id",
          "incident_id",
          "patient_no",
          "registration_status",
          "current_tag",
          "start_tag",
          "pat_tag",
          "injury_details",
          "registered_by_team_id",
          "confirmed_by_team_id",
          "assigned_team_id",
          "assigned_hospital_id",
          "transport_assignment_id",
        ],
        indexes: ["idx_triage_patients_incident_tag", "idx_triage_patients_assignment"],
      },
      {
        table: "triage_hospital_requests",
        columns: [
          "id",
          "incident_id",
          "request_id",
          "hospital_id",
          "status",
          "disaster_summary",
          "start_counts",
          "pat_counts",
          "notes",
          "created_by_user_id",
          "sent_at",
        ],
        indexes: [
          "idx_triage_hospital_requests_incident_status",
          "idx_triage_hospital_requests_hospital_status",
        ],
      },
      {
        table: "triage_hospital_offers",
        columns: [
          "id",
          "request_id",
          "hospital_id",
          "red_capacity",
          "yellow_capacity",
          "green_capacity",
          "black_capacity",
          "notes",
          "responded_by_user_id",
          "responded_at",
        ],
      },
      {
        table: "triage_transport_assignments",
        columns: [
          "id",
          "incident_id",
          "hospital_offer_id",
          "hospital_id",
          "team_id",
          "status",
          "assigned_by_team_id",
          "sent_at",
          "decided_at",
        ],
        indexes: [
          "idx_triage_transport_assignments_incident_status",
          "idx_triage_transport_assignments_team_status",
        ],
      },
    ],
    "Run npm run db:migrate to apply migration_20260427_0020_mci_triage_incidents.sql.",
  );
}
