import { assertSchemaRequirements } from "@/lib/schemaRequirements";

export async function ensureTriageIncidentTables(): Promise<void> {
  await assertSchemaRequirements(
    "ensureTriageIncidentTables",
    [
      {
        table: "triage_incidents",
        columns: [
          "id",
          "incident_code",
          "source_case_uid",
          "mode",
          "status",
          "address",
          "aware_date",
          "summary",
          "notes",
          "created_by_team_id",
          "approved_by_dispatch_user_id",
          "command_team_id",
          "closure_type",
          "closure_reason",
          "closed_by_user_id",
          "closure_review",
          "start_red_count",
          "start_yellow_count",
          "start_green_count",
          "start_black_count",
          "pat_red_count",
          "pat_yellow_count",
          "pat_green_count",
          "pat_black_count",
        ],
        indexes: [
          "idx_triage_incidents_source_case_uid",
          "idx_triage_incidents_mode_status_updated",
          "idx_triage_incidents_command_team",
        ],
      },
      {
        table: "triage_incident_teams",
        columns: [
          "id",
          "incident_id",
          "team_id",
          "role",
          "participation_status",
          "operational_mode_at_request",
          "triage_mode_requested_at",
          "triage_mode_acknowledged_at",
          "command_requested_at",
          "command_request_note",
          "last_seen_at",
        ],
        indexes: [
          "idx_triage_incident_teams_incident_role",
          "idx_triage_incident_teams_team_status",
        ],
      },
      {
        table: "triage_patients",
        columns: [
          "id",
          "incident_id",
          "patient_no",
          "provisional_patient_no",
          "registration_status",
          "current_tag",
          "start_tag",
          "pat_tag",
          "injury_details",
          "registered_by_team_id",
          "confirmed_by_team_id",
          "reviewed_by_team_id",
          "reviewed_at",
          "review_reason",
          "merged_into_patient_id",
          "start_algorithm_version_id",
          "pat_algorithm_version_id",
          "assigned_team_id",
          "assigned_hospital_id",
          "transport_assignment_id",
        ],
        indexes: [
          "idx_triage_patients_incident_tag",
          "idx_triage_patients_assignment",
          "idx_triage_patients_incident_patient_no_confirmed",
          "idx_triage_patients_incident_provisional_no",
          "idx_triage_patients_review_queue",
        ],
      },
      {
        table: "triage_hospital_requests",
        columns: [
          "id",
          "incident_id",
          "request_id",
          "hospital_id",
          "status",
          "disaster_summary",
          "start_counts",
          "pat_counts",
          "notes",
          "created_by_user_id",
          "sent_at",
        ],
        indexes: [
          "idx_triage_hospital_requests_incident_status",
          "idx_triage_hospital_requests_hospital_status",
        ],
      },
      {
        table: "triage_hospital_offers",
        columns: [
          "id",
          "request_id",
          "hospital_id",
          "red_capacity",
          "yellow_capacity",
          "green_capacity",
          "black_capacity",
          "notes",
          "responded_by_user_id",
          "responded_at",
          "expires_at",
          "cancelled_at",
          "cancel_reason",
          "cancelled_by_user_id",
        ],
      },
      {
        table: "triage_transport_assignments",
        columns: [
          "id",
          "incident_id",
          "hospital_offer_id",
          "hospital_id",
          "team_id",
          "status",
          "assigned_by_team_id",
          "sent_at",
          "decided_at",
          "declined_at",
          "decline_reason",
          "departed_at",
          "arrived_at",
          "handoff_completed_at",
          "handoff_by_user_id",
        ],
        indexes: [
          "idx_triage_transport_assignments_incident_status",
          "idx_triage_transport_assignments_team_status",
          "idx_triage_transport_assignments_offer_status",
        ],
      },
      {
        table: "triage_algorithm_versions",
        columns: [
          "id",
          "method",
          "version",
          "status",
          "rules_summary",
          "approved_by_user_id",
          "approved_at",
          "retired_at",
        ],
        indexes: ["idx_triage_algorithm_versions_one_approved"],
      },
      {
        table: "triage_patient_tag_events",
        columns: [
          "id",
          "incident_id",
          "patient_id",
          "from_tag",
          "to_tag",
          "reason",
          "source",
          "start_algorithm_version_id",
          "pat_algorithm_version_id",
          "acted_by_team_id",
          "acted_by_user_id",
          "acted_at",
        ],
        indexes: ["idx_triage_patient_tag_events_patient", "idx_triage_patient_tag_events_incident"],
      },
      {
        table: "triage_incident_command_transitions",
        columns: [
          "id",
          "incident_id",
          "from_team_id",
          "to_team_id",
          "reason",
          "requested_by_team_id",
          "approved_by_user_id",
          "transitioned_at",
        ],
        indexes: ["idx_triage_incident_command_transitions_incident"],
      },
      {
        table: "triage_audit_events",
        columns: [
          "id",
          "incident_id",
          "incident_code",
          "mode",
          "event_type",
          "actor_user_id",
          "actor_team_id",
          "actor_hospital_id",
          "target_type",
          "target_id",
          "payload",
          "created_at",
        ],
        indexes: ["idx_triage_audit_events_incident", "idx_triage_audit_events_type"],
      },
      {
        table: "triage_incident_reports",
        columns: ["id", "incident_id", "report_json", "generated_by_user_id", "generated_at", "updated_at"],
      },
    ],
    "Run npm run db:migrate to apply migration_20260427_0020_mci_triage_incidents.sql and migration_20260505_0021_mci_triage_p0_foundations.sql.",
  );
}
